config/routes.rb
Rails.application.routes.draw do
  root "habits#index"
  
  resources :supports #, only: [:create,:destroy] 
  resources :steps #, except: [:index,:show]  REVIEW
  resources :friend_requests #, except: [:index,:show,:new,:edit]
  resources :habits #, except: [:index,:show]  REVIEW
  devise_for :users

  get "all" => "users#all", as: :all
  get ":username" => "users#show", as: :profile
  get ":username/progress" => "users#progress", as: :progress
  get ":username/feed" => "users#feed", as: :feed
  get ":username/friends" => "users#friends", as: :friends
  get ":username/pending" => "users#pending", as: :pending
  get ":username/steps" => "users#steps", as: :usersteps
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  comments_count         :integer          default(0)
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  habits_count           :integer          default(0)
#  private                :boolean          default(FALSE)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  supports_count         :integer          default(0)
#  username               :citext
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  
  has_many :own_habits, foreign_key: :owner_id, class_name: "Habit", dependent: :destroy

  has_many :sent_friend_requests, foreign_key: :sender_id,  class_name: "FriendRequest", dependent: :destroy
  has_many :received_friend_requests, foreign_key: :recipient_id,  class_name: "FriendRequest", dependent: :destroy

  #Friends sender and receipent
  has_many :accepted_sent_friend_requests, ->{ accepted }, foreign_key: :sender_id,  class_name: "FriendRequest"
  has_many :accepted_received_friend_requests, ->{ accepted }, foreign_key: :recipient_id,  class_name: "FriendRequest"
  has_many :pending_received_friend_requests, ->{ pending }, foreign_key: :recipient_id,  class_name: "FriendRequest"

  has_many :supports, foreign_key: :fan_id, dependent: :destroy

  #Indirect associations:
  has_many :own_steps, through: :own_habits, source: :steps
  has_many :supported_steps, through: :supports, source: :step
  
  has_many :friends_r, through: :accepted_sent_friend_requests, source: :recipient
  has_many :friends_s, through: :accepted_received_friend_requests, source: :sender

  def friend_ids
    (friends_r.ids + friends_s.ids).uniq
  end

  def friends
    User.where(id: friend_ids)
  end

  has_many :feed_s, through: :friends_s, source: :own_steps
  has_many :feed_r, through: :friends_r, source: :own_steps
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  #respond_to :json
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def all
    @users = User.all
  end

  def steps
    if params[:username]
      @user = User.find_by!(username: params.fetch(:username))
    else
      @user = current_user
    end

    respond_to do |format|
      format.html
      format.json

    end


  end
  
  def feed
    if params[:username]
      @user = User.find_by!(username: params.fetch(:username))
    else
      @user = current_user
    end
   
    people = @user.friend_ids
    theirhabits = Habit.where(owner_id: people)
    habitsid = theirhabits.ids
    @prefeed = Step.where(habit_id: habitsid).order(created_at: "DESC")

    respond_to do |format|
      format.html
      format.json

    end
  end

  def progress
    if params[:username]
      @user = User.find_by!(username: params.fetch(:username))
    else
      @user = current_user
    end
    @habits = @user.own_habits

    respond_to do |format|
      format.html 
      format.json 

    end
  end

  def friends
    if params[:username]
      @user = User.find_by!(username: params.fetch(:username))
    else
      @user = current_user
    end

    @friends_sent = @user.accepted_sent_friend_requests
    @friends_received = @user.accepted_received_friend_requests

    respond_to do |format|
      format.html 
      format.json 

    end
  end

  def pending
    if params[:username]
      @user = User.find_by!(username: params.fetch(:username))
    else
      @user = current_user
    end
    @pendings = @user.pending_received_friend_requests

    respond_to do |format|
      format.html 
      format.json 

    end
  end

  def show
    if params[:username]
      @user = User.find_by!(username: params.fetch(:username))
    else
      @user = current_user
    end
  
  end


end 

app/views/users/all.html.erb
<% @users.each do |user|%>
  <br><%= user.username %>
  <br><%= user.id %>
  <br><%= user.email %>
<%end %>

app/views/users/feed.html.erb
hola
<% @feed1.each do |fr| %>
 <tr>
 <td><%= fr.username %></td>
 <td><%= fr.id %> </td>
 <% fr.own_steps.each do |st|%>
    <td><%= st.habit.title %></td>
    <td><%= st.id %></td>
  <%end%>
  </tr>
<%end%>

<% @feed.each do |fr| %>
 <tr>
 <td><%= fr.id %> </td>

<%end%>

app/views/users/progress.html.erb
<h1>Habits</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Habit type</th>
      <th>Frequency</th>
      <th>Goal frequency</th>
      <th>Private</th>
      <th>Current progress</th>
      <th>Top streak</th>
      <th>Owner</th>
      <th>Steps count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <tr>
        <td><%= habit.title %></td>
        <td><%= habit.description %></td>
        <td><%= habit.habit_type %></td>
        <td><%= habit.frequency %></td>
        <td><%= habit.goal_frequency %></td>
        <td><%= habit.private %></td>
        <td><%= habit.current_progress %></td>
        <td><%= habit.top_streak %></td>
        <td><%= habit.owner_id %></td>
        <td><%= habit.steps_count %></td>
        <td><%= link_to 'Show', habit %></td>
        <td><%= link_to 'Edit', edit_habit_path(habit) %></td>
        <td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Habit', new_habit_path %>

app/views/users/show.html.erb
<%= @user.username%>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Habit type</th>
      <th>Frequency</th>
      <th>Goal frequency</th>
      <th>Private</th>
      <th>Current progress</th>
      <th>Top streak</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.own_habits.each do |habit| %>
      <tr>
        <td><%= habit.title %></td>
        <td><%= habit.description %></td>
        <td><%= habit.habit_type %></td>
        <td><%= habit.frequency %></td>
        <td><%= habit.goal_frequency %></td>
        <td><%= habit.private %></td>
        <td><%= habit.current_progress %></td>
        <td><%= habit.top_streak %></td>
        <td><%= habit.owner.username %></td>
        <td><%= link_to 'Show', habit %></td>
        <td><%= link_to 'Edit', edit_habit_path(habit) %></td>
        <td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<table>
  <thead>
    <tr>
      <th>Caption</th>
      <th>Image</th>
      <th>Supports count</th>
      <th>Habit</th>
      <th>Owner</th>
      <th>Date completion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.own_steps.each do |action| %>
      <tr>
        <td><%= action.caption %></td>
        <td><%= action.image %></td>
        <td><%= action.supports_count %></td>
        <td><%= action.habit.title %></td>
        <td><%= action.owner.username %></td>
        <td><%= action.date_completion %></td>
        <td><%= link_to 'Show', action %></td>
        <td><%= link_to 'Edit', edit_step_path(action) %></td>
        <td><%= link_to 'Destroy', action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    
  </tbody>
</table>

<br>