config/routes.rb
Rails.application.routes.draw do
  root "habits#index"
  
  resources :supports #, only: [:create,:destroy] 
  resources :steps #, except: [:index,:show]  REVIEW
  resources :friend_requests #, except: [:index,:show,:new,:edit]
  resources :habits #, except: [:index,:show]  REVIEW
  devise_for :users

  get "all" => "users#all", as: :all
  get ":username" => "users#show", as: :profile
  get ":username/progress" => "users#progress", as: :progress
  get ":username/feed" => "users#feed", as: :feed
  get ":username/friends" => "users#friends", as: :friends
  get ":username/pending" => "users#pending", as: :pending
  get ":username/steps" => "users#steps", as: :usersteps
end

app/models/friend_request.rb
# == Schema Information
#
# Table name: friend_requests
#
#  id           :bigint           not null, primary key
#  status       :string           default("pending")
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  recipient_id :bigint           not null
#  sender_id    :bigint           not null
#
# Indexes
#
#  index_friend_requests_on_recipient_id  (recipient_id)
#  index_friend_requests_on_sender_id     (sender_id)
#
# Foreign Keys
#
#  fk_rails_...  (recipient_id => users.id)
#  fk_rails_...  (sender_id => users.id)
#
class FriendRequest < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"

  enum status: { pending: "pending", rejected: "rejected", accepted: "accepted" }
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :set_friend_request, only: %i[ show edit update destroy ]

  # GET /friend_requests or /friend_requests.json
  def index
    @friend_requests = FriendRequest.all
  end

  # GET /friend_requests/1 or /friend_requests/1.json
  def show
  end

  # GET /friend_requests/new
  def new
    @friend_request = FriendRequest.new
  end

  # GET /friend_requests/1/edit
  def edit
  end

  # POST /friend_requests or /friend_requests.json
  def create
    @friend_request = FriendRequest.new(friend_request_params)

    respond_to do |format|
      if @friend_request.save
        format.html { redirect_to friend_request_url(@friend_request), notice: "Friend request was successfully created." }
        format.json { render :show, status: :created, location: @friend_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_requests/1 or /friend_requests/1.json
  def update

    respond_to do |format|
      if @friend_request.update(friend_request_params)
        format.html { redirect_to friend_request_url(@friend_request), notice: "Friend request was successfully updated." }
        format.json { render :show, status: :ok, location: @friend_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_requests/1 or /friend_requests/1.json
  def destroy
    # A friend_request should be only destroy by the people involved
    #if @friend_request.sender!= current_user && @friend_request.recipient != current_user
    #  redirect_back(fallback_location: root_url, alert: "Not authorized")
    #else 
    @friend_request.destroy

      respond_to do |format|
        format.html { redirect_to friend_requests_url, notice: "Friend request was successfully destroyed." }
        format.json { head :no_content }
    # end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_request
      @friend_request = FriendRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_request_params
      params.require(:friend_request).permit(:recipient_id, :sender_id, :status)
    end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_form.html.erb
<%= form_with(model: friend_request) do |form| %>
  <% if friend_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend_request.errors.count, "error") %> prohibited this friend_request from being saved:</h2>

      <ul>
        <% friend_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipient_id %>
    <%= form.text_field :recipient_id %>
  </div>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.text_field :sender_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friend_requests/edit.html.erb
<h1>Editing Friend Request</h1>

<%= render 'form', friend_request: @friend_request %>

<%= link_to 'Show', @friend_request %> |
<%= link_to 'Back', friend_requests_path %>

app/views/friend_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friend Requests</h1>

<table>
  <thead>
    <tr>
      <th>Recipient</th>
      <th>Sender</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friend_requests.each do |friend_request| %>
      <tr>
        <td><%= friend_request.recipient_id %></td>
        <td><%= friend_request.sender_id %></td>
        <td><%= friend_request.status %></td>
        <td><%= link_to 'Show', friend_request %></td>
        <td><%= link_to 'Edit', edit_friend_request_path(friend_request) %></td>
        <td><%= link_to 'Destroy', friend_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend Request', new_friend_request_path %>

app/views/friend_requests/new.html.erb
<h1>New Friend Request</h1>

<%= render 'form', friend_request: @friend_request %>

<%= link_to 'Back', friend_requests_path %>

app/views/friend_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient:</strong>
  <%= @friend_request.recipient_id %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @friend_request.sender_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @friend_request.status %>
</p>

<%= link_to 'Edit', edit_friend_request_path(@friend_request) %> |
<%= link_to 'Back', friend_requests_path %>