config/routes.rb
Rails.application.routes.draw do
  root "habits#index"
  
  resources :supports #, only: [:create,:destroy] 
  resources :steps #, except: [:index,:show]  REVIEW
  resources :friend_requests #, except: [:index,:show,:new,:edit]
  resources :habits #, except: [:index,:show]  REVIEW
  devise_for :users

  get "all" => "users#all", as: :all
  get ":username" => "users#show", as: :profile
  get ":username/progress" => "users#progress", as: :progress
  get ":username/feed" => "users#feed", as: :feed
  get ":username/friends" => "users#friends", as: :friends
  get ":username/pending" => "users#pending", as: :pending
  get ":username/steps" => "users#steps", as: :usersteps
end

app/models/support.rb
# == Schema Information
#
# Table name: supports
#
#  id           :bigint           not null, primary key
#  support_type :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  fan_id       :bigint           not null
#  step_id      :bigint           not null
#
# Indexes
#
#  index_supports_on_fan_id   (fan_id)
#  index_supports_on_step_id  (step_id)
#
# Foreign Keys
#
#  fk_rails_...  (fan_id => users.id)
#  fk_rails_...  (step_id => steps.id)
#
class Support < ApplicationRecord
  belongs_to :fan, class_name: "User", counter_cache: true, dependent: :destroy
  belongs_to :step, counter_cache: true, dependent: :destroy

  has_one :owner, through: :step

  enum support_type: {like: "like", love: "love", celebrate: "celebrate" }
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :set_support, only: %i[ show edit update destroy ]

  # GET /supports or /supports.json
  def index
    @supports = Support.all
  end

  # GET /supports/1 or /supports/1.json
  def show
  end

  # GET /supports/new
  def new
    @support = Support.new
  end

  # GET /supports/1/edit
  def edit
  end

  # POST /supports or /supports.json
  def create
    @support = Support.new(support_params)

    respond_to do |format|
      if @support.save
        format.html { redirect_to support_url(@support), notice: "Support was successfully created." }
        format.json { render :show, status: :created, location: @support }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supports/1 or /supports/1.json
  def update
    respond_to do |format|
      if @support.update(support_params)
        format.html { redirect_to support_url(@support), notice: "Support was successfully updated." }
        format.json { render :show, status: :ok, location: @support }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supports/1 or /supports/1.json
  def destroy
    # A support should be only destroy by the people involved
    #if @support.owner!= current_user && @support.fan != current_user
    #  redirect_back(fallback_location: root_url, alert: "Not authorized")
    #else 
      @support.destroy

      respond_to do |format|
        format.html { redirect_to supports_url, notice: "Support was successfully destroyed." }
        format.json { head :no_content }
      end
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support
      @support = Support.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def support_params
      params.require(:support).permit(:support_type, :fan_id, :step_id)
    end
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/supports/_form.html.erb
<%= form_with(model: support) do |form| %>
  <% if support.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(support.errors.count, "error") %> prohibited this support from being saved:</h2>

      <ul>
        <% support.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :support_type %>
    <%= form.text_field :support_type %>
  </div>

  <div class="field">
    <%= form.label :fan_id %>
    <%= form.text_field :fan_id %>
  </div>

  <div class="field">
    <%= form.label :step_id %>
    <%= form.text_field :step_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/supports/edit.html.erb
<h1>Editing Support</h1>

<%= render 'form', support: @support %>

<%= link_to 'Show', @support %> |
<%= link_to 'Back', supports_path %>

app/views/supports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Supports</h1>

<table>
  <thead>
    <tr>
      <th>Support type</th>
      <th>Fan</th>
      <th>Step</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supports.each do |support| %>
      <tr>
        <td><%= support.support_type %></td>
        <td><%= support.fan_id %></td>
        <td><%= support.step_id %></td>
        <td><%= link_to 'Show', support %></td>
        <td><%= link_to 'Edit', edit_support_path(support) %></td>
        <td><%= link_to 'Destroy', support, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Support', new_support_path %>

app/views/supports/new.html.erb
<h1>New Support</h1>

<%= render 'form', support: @support %>

<%= link_to 'Back', supports_path %>

app/views/supports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Support type:</strong>
  <%= @support.support_type %>
</p>

<p>
  <strong>Fan:</strong>
  <%= @support.fan_id %>
</p>

<p>
  <strong>Step:</strong>
  <%= @support.step_id %>
</p>

<%= link_to 'Edit', edit_support_path(@support) %> |
<%= link_to 'Back', supports_path %>