config/routes.rb
Rails.application.routes.draw do
  root "habits#index"
  
  resources :supports #, only: [:create,:destroy] 
  resources :steps #, except: [:index,:show]  REVIEW
  resources :friend_requests #, except: [:index,:show,:new,:edit]
  resources :habits #, except: [:index,:show]  REVIEW
  devise_for :users

  get "all" => "users#all", as: :all
  get ":username" => "users#show", as: :profile
  get ":username/progress" => "users#progress", as: :progress
  get ":username/feed" => "users#feed", as: :feed
  get ":username/friends" => "users#friends", as: :friends
  get ":username/pending" => "users#pending", as: :pending
  get ":username/steps" => "users#steps", as: :usersteps
end

app/models/habit.rb
# == Schema Information
#
# Table name: habits
#
#  id               :bigint           not null, primary key
#  current_progress :float            default(0.0)
#  description      :text
#  frequency        :string           not null
#  goal_frequency   :integer          not null
#  habit_type       :string           not null
#  private          :boolean          default(FALSE)
#  steps_count      :integer          default(0)
#  title            :string           not null
#  top_streak       :float            default(0.0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  owner_id         :bigint           not null
#
# Indexes
#
#  index_habits_on_owner_id  (owner_id)
#
# Foreign Keys
#
#  fk_rails_...  (owner_id => users.id)
#
class Habit < ApplicationRecord
  belongs_to :owner, class_name: "User", counter_cache: true

  has_many :steps, dependent: :destroy
 
  enum frequency: {daily: "daily", weekly: "weekly", monthly: "monthly" }
  enum habit_type: {health: "health", productivity: "productivity", other: "other"}
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: %i[ show edit update destroy ]

  # GET /habits or /habits.json
  def index
    @habits = Habit.all
  end

  # GET /habits/1 or /habits/1.json
  def show
  end

  # GET /habits/new
  def new
    @habit = Habit.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits or /habits.json
  def create
    @habit = Habit.new(habit_params)

    respond_to do |format|
      if @habit.save
        format.html { redirect_to habit_url(@habit), notice: "Habit was successfully created." }
        format.json { render :show, status: :created, location: @habit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1 or /habits/1.json
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        format.html { redirect_to habit_url(@habit), notice: "Habit was successfully updated." }
        format.json { render :show, status: :ok, location: @habit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1 or /habits/1.json
  def destroy
    @habit.destroy

    respond_to do |format|
      format.html { redirect_to habits_url, notice: "Habit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def habit_params
      params.require(:habit).permit(:title, :description, :habit_type, :frequency, :goal_frequency, :private, :current_progress, :top_streak, :owner_id, :steps_count)
    end
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/habits/_form.html.erb
<%= form_with(model: habit) do |form| %>
  <% if habit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(habit.errors.count, "error") %> prohibited this habit from being saved:</h2>

      <ul>
        <% habit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :habit_type %>
    <%= form.text_field :habit_type %>
  </div>

  <div class="field">
    <%= form.label :frequency %>
    <%= form.text_field :frequency %>
  </div>

  <div class="field">
    <%= form.label :goal_frequency %>
    <%= form.number_field :goal_frequency %>
  </div>

  <div class="field">
    <%= form.label :private %>
    <%= form.check_box :private %>
  </div>

  <div class="field">
    <%= form.label :current_progress %>
    <%= form.text_field :current_progress %>
  </div>

  <div class="field">
    <%= form.label :top_streak %>
    <%= form.text_field :top_streak %>
  </div>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.text_field :owner_id %>
  </div>

  <div class="field">
    <%= form.label :steps_count %>
    <%= form.number_field :steps_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/habits/edit.html.erb
<h1>Editing Habit</h1>

<%= render 'form', habit: @habit %>

<%= link_to 'Show', @habit %> |
<%= link_to 'Back', habits_path %>

app/views/habits/index.html.erb
<h1>Habits</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Habit type</th>
      <th>Frequency</th>
      <th>Goal frequency</th>
      <th>Private</th>
      <th>Current progress</th>
      <th>Top streak</th>
      <th>Owner</th>
      <th>Steps count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <tr>
        <td><%= habit.title %></td>
        <td><%= habit.description %></td>
        <td><%= habit.habit_type %></td>
        <td><%= habit.frequency %></td>
        <td><%= habit.goal_frequency %></td>
        <td><%= habit.private %></td>
        <td><%= habit.current_progress %></td>
        <td><%= habit.top_streak %></td>
        <td><%= habit.owner_id %></td>
        <td><%= habit.steps_count %></td>
        <td><%= link_to 'Show', habit %></td>
        <td><%= link_to 'Edit', edit_habit_path(habit) %></td>
        <td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Habit', new_habit_path %>

app/views/habits/new.html.erb
<h1>New Habit</h1>

<%= render 'form', habit: @habit %>

<%= link_to 'Back', habits_path %>

app/views/habits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @habit.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @habit.description %>
</p>

<p>
  <strong>Habit type:</strong>
  <%= @habit.habit_type %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @habit.frequency %>
</p>

<p>
  <strong>Goal frequency:</strong>
  <%= @habit.goal_frequency %>
</p>

<p>
  <strong>Private:</strong>
  <%= @habit.private %>
</p>

<p>
  <strong>Current progress:</strong>
  <%= @habit.current_progress %>
</p>

<p>
  <strong>Top streak:</strong>
  <%= @habit.top_streak %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @habit.owner_id %>
</p>

<p>
  <strong>Steps count:</strong>
  <%= @habit.steps_count %>
</p>

<%= link_to 'Edit', edit_habit_path(@habit) %> |
<%= link_to 'Back', habits_path %>